### ISSUE TITLE
[ROADMAP] Sprint3

### ISSUE THREAD

**Issue by lkorczowski** [bertrandlalo/timeflux_rasr#15]
### SPRINT BACKLOG
_in chronological order_
- [x] extensive pytest (each breaking point in RASR and related functions), see #24 
- [x] REFACTORING: remove completely the 2D compatibility > only 3D matrices will be managed. removing related parameters (window_len, window_overlap, etc.) and epoching steps. See #5 
- [x] passing the parameters from RASR to _fit_eeg_distribution() and checking valid keys. See https://github.com/bertrandlalo/timeflux_rasr/issues/15#issuecomment-585231931 
- [ ] more documentation (insure accurate explanation of parameters, add instruction to how epoch the data before feeding to RASR)
- [x] blending (with parameter for option), see https://github.com/bertrandlalo/timeflux_rasr/issues/15#issuecomment-584583649
- [ ]  detailed report for python rasr behaviour for different parameters (with comparison with matlab using default parameters) (e.g. screenshot, description, analysis of the outliers, etc.)
- [ ] Visually validate on a new dataset

### PRODUCT BACKLOG (out of scope)
- IIR filter for mixing matrix and reconstruction matrix estimation #10 
- solve the pymanopt converge of non_linear_eigh(), see #14

**Comment by lkorczowski** [comment]
FYI 1bf6683 added a feature for testing and passing **kwargs arguments properly while still checking for invalids key parameters. feature done

**Comment by lkorczowski** [comment]
@mesca could you send me another dataset of analysis? Thanks

**Comment by lkorczowski** [comment]
@mesca in news on the #27 review ?

**Comment by lkorczowski** [comment]
#27 and #30 fixed most of the points

#34 tested on new dataset
