### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by lkorczowski** [bertrandlalo/timeflux_rasr#24]
I'm attacking the task to maximize the coverage. I'm following the sklearn [guideline](https://scikit-learn.org/stable/developers/contributing.html#testing-and-improving-test-coverage) and the proposed [template](https://github.com/scikit-learn-contrib/project-template/blob/master/skltemplate/_template.py), I hope that we will see a lot of improvement. We can discuss this topic here.

### Roadmap for sprint3 #15 
- [x] install and work with coverage
- [x] estimation.RASR covered 100%
- [x] estimation._fit_eeg_distribution covered 100%
- [x] estimation._rms covered 100%
- [x] utils.utils covered 100%
- [x] utils.viz covered 100% WITH [test fixtures](https://scikit-learn.org/stable/developers/contributing.html#testing-and-improving-test-coverage) (because using matplotlib)

**Comment by lkorczowski** [comment]
as #26 84%
```
Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
tests/__init__.py                 0      0   100%
tests/conftest.py                 8      0   100%
tests/test_config.py              9      0   100%
tests/test_estimation.py         94      1    99%   134
tests/test_utils.py              99     16    84%   50-58, 123-125, 132-135
tests/test_viz.py                42      0   100%
timeflux_rasr/__init__.py         1      0   100%
timeflux_rasr/estimation.py     151      0   100%
utils/__init__.py                 4      0   100%
utils/config.py                  20      1    95%   30
utils/utils.py                  143     78    45%   15, 27-35, 48-51, 67-90, 110-127, 147-185, 193-196, 201-205
utils/viz.py                     47      0   100%
-----------------------------------------------------------
TOTAL                           618     96    84%
```
