### ISSUE TITLE
[ROADMAP] Sprint2

### ISSUE THREAD

**Issue by lkorczowski** [bertrandlalo/timeflux_rasr#8]
Hi,

2020-01-15: update after the meeting. To validate sprint 2, we missed three functionalities. See below for the updated delivery.
~~Following the 2019-12-11 meeting, here are the roadmap for the second sprint:~~

## Summary 
Delivery scenario: "I can use RASR module in Timeflux just as I call any other sklearn-like node"
Delivery criteria:
- [x] qualitative (e.g. visual inspection and comparison with matlab implementation, etc.), see #17 
- [x] ~~quantitative (e.g. classification, some automatic noise metric, etc.)~~(update 20200115: out of scope due to difficulty to find a relevent metric)
- [x] computational (e.g. max execution delay in ms), see #17 

### Details
_Important decision are required, see below to answer in the related issues_
- [x] have a python/jupyter script with fig and results as output for comparison that shows that the criteria are reached (see script_RASR_comparison and #17 )
- ~~[ ] have a test scenario in Timeflux using RASR module~~ (managed by @mesca )
- [x] find a best solution to implement the PGA either using hess/grad function (required some way to double check if correct), see #6, and/or by using autograd/thenao with pymanopt (optional), see #7 . (update 20200115: pymanopt doesn't converge, follow up in #14, see #18 for related PR)
- [x] decide and implement the input data structure with sklearn/pyriemann/mne/timeflux interoperability in mind, see #5 
- [x] decide whether or not we use an adaptive reconstruction matrix (R) with raised-cosine blending as in matlab implementation in transform() (not sklearn friendly) or with a second function like "adaptive_transform()", see #4 and #2 (update 20200115: I will send a recommendation for the blending, update: see #15 )
- [x] decide the qualitative, quantitative and computational criteria. (update 20200115: quantitative is harder than expected to find a relevant metrics.)

### additional features implemented
- [x] few pytest for estimation.RASR and core function (_fit_eeg_distribution)

~~### To implement but Not included in this sprint~~
_(obsolete, see https://github.com/bertrandlalo/timeflux_rasr/issues/8#issuecomment-574721718 for new backlog)_
- unit test
- documentation
- tuto 

### ideas
- riemannian geometric median, see #3
